export enum FantasyScoringRules {
  TwoPointConversions = 2,
  PassYards = 0.04,
  PassAttempts = 0,
  PassTD = 4,
  PassCompletions = 0,
  PassInterceptions = -2,
  PointsPerReception = 0.5,
  Carries = 0.2,
  RushYards = 0.1,
  RushTD = 6,
  Fumbles = -2,
  ReceivingYards = 0.1,
  ReceivingTD = 6,
  Targets = 0,
  DefTD = 6,
  FgMade = 3,
  FgMissed = -3,
  XpMade = 1,
  XpMissed = -1,
}
