services:
  database:
    image: mysql:latest
    ports:
      - '3306:3306'
    hostname: database
    env_file:
      - ./.env
    environment:
      DATABASE_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_USER: '${DATABASE_USER}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DATABASE_HOST: '${DATABASE_HOST}'
    volumes:
      - feed-volume:/var/lib/mysql
      - ./src/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          '127.0.0.1',
          '--user=$DATABASE_USER',
          '--password=$DATABASE_PASSWORD',
        ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  feed-volume:
