services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    hostname: database
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_HOST: '${DATABASE_HOST}'
    volumes:
      - feed-volume:/var/lib/postgresql/data
      # If you need to initialize the PostgreSQL database with custom SQL scripts:
      # - ./src/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  feed-volume:
