services:
  database:
    image: mysql:latest
    ports:
      - '3306:3306'
    hostname: database
    env_file:
      - ./.env
    volumes:
      - feed-volume:/var/lib/mysql
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  feed-volume:
