service: lambda-api-gateway

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2

functions:
  mainFunction:
    handler: build/handler.mainHandler
    timeout: 30
    events:
      - http:
          path: /hellokian
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
