service: lambda-api-gateway

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: 'stats' # Default to 'dev' if not specified

functions:
  mainFunction:
    handler: build/handler.mainHandler
    timeout: 30
    events:
      - http:
          path: /hellokian
          method: get
          cors: true
  getWrStats:
    handler: build/handler.getWrStats
    timeout: 30
    events:
      - http:
          path: /getWrStats
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
